language: ruby
cache: bundler # caching to speed up dependency installation
rvm:
- 2.5.0
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
script:
jobs:
  include:
    - stage: build
      script: script/build
    - stage: testlinks
      script: script/testlinks
